miroapp/app-examples

- README.md
- examples/blob-maker/README.md
- examples/blob-maker/index.html
- examples/calendar/README.md
- examples/drag-and-drop/README.md
- examples/oauth/node/README.md
- examples/oauth/node/index.js
- examples/oauth/python/oauth_example.py
- examples/rest-stickies-csv/README.md
- examples/rest-stickies-csv/authorization/auth.js
- examples/rest-stickies-csv/views/authorizeApp.hbs
- examples/rest-stickies-csv/views/home.hbs
- examples/stickynotes-to-shapes/README.md
- examples/template-builder/README.md
- examples/wordle/README.md
- examples/youtube-room/README.md
- examples/youtube-room/facilitator.html
- examples/youtube-room/index.html
- examples/youtube-room/participant.html
- remove 'beta' occurrences
- fix typos
- update docs links
- minor edits to improve consistency
> Remove beta occurrences

- .gitignore
- examples/REST/python-flask-starter/README.md
- examples/REST/python-flask-starter/app.py
- examples/REST/python-flask-starter/requirements.txt
- examples/REST/python-flask-starter/sample.env
- examples/REST/python-flask-starter/templates/index.html
- examples/REST/python-flask-starter/templates/loggedin.html
This sample Flask/Python project will allow developers to start using the REST API in a few minutes
_Project build by @joannasmith_
> Python Flask starter

- CODEOWNERS
Adding DevX to `app-examples` `CODEOWNERS` to not bottleneck updates
> Add devx to codeowners

- examples/rest-stickies-csv/app.js
Add V2 REST [Connectors](https://developers.miro.com/reference/create-connector) to rest-stickies-csv sample app.
> add connectors to rest-stickies-csv sample

- examples/node-stickies-csv/README.md
- examples/node-stickies-csv/app.js
- examples/node-stickies-csv/package.json
- yarn.lock
* Update occurrences of the npm package name 'miro-node' to 'miro-api.
* Update package version to `1.0.0`
* Edit README file to improve consistency with similar content in the other sample apps.
> Dx 1362 update 'miro-node' to 'miro-api. Update its version to 1.0.0 

- README.md
- examples/github-appcards/README.md
- examples/nextjs-full-stack/README.md
- examples/nextjs-oauth/README.md
- examples/nextjs-oauth/pages/index.js
* Add code comments to describe env vars in Vite `.env` file: a follow-up to issue https://github.com/miroapp/app-examples/issues/80
* Add link to the complementary complete tutorial on dev docs
* Hyphenate "full stack" to "full-stack" when it is used as an adjective/modifier
> DX-1188 Add code comments to describe env vars in .env file

- examples/webhooks-manager/pages/index.tsx
- examples/webhooks-manager/styles/globals.css
- Remove extra hr when no webhooks
- Add scrollbar when panel is too small to fit contents
> Adjust UI for webhooks

- examples/asset-search/package.json
- examples/wordle/package.json
> App description updates

- examples/asset-search/README.md
- examples/calendar/README.md
- examples/drag-and-drop/README.md
- examples/github-appcards/README.md
- examples/wordle/README.md
- examples/wordle/package.json
> updated app descriptions

- examples/node-oauth/app-manifest.yaml
> Update app name

- examples/csv-to-mindmap/src/mindmap.ts
> Update CSV to mindmap app

- examples/calendar/README.md
* add gif
* add included components 
adding screenshots below of the update:
> updating calendar app with standard README template

- examples/calendar/README.md
- examples/csv-to-mindmap/README.md
- examples/drag-and-drop/README.md
- examples/stickynotes-to-shapes/README.md
- examples/template-builder/README.md
- examples/wordle/README.md
Updated 4 app-examples to be in the same style / template as drag and drop and added demo videos / gifs:
* CSV to Mindmap
* Stickynotes-to-shapes
* Template Builder
* Wordle
> Hporutiu update readme with template

- examples/ai-image-generator/.env.sample
- examples/ai-image-generator/README.md
- examples/ai-image-generator/app-manifest.yaml
- examples/ai-image-generator/pages/api/openai.js
just cleaned up the app a bit, mostly took out redirect URL.
> taking out redirect urls, client secret etc

- examples/ai-image-generator/README.md
Title says it all. Adding the YouTube video to the README itself to help devs if they prefer to watch video content.
> adding youtube video to README

- examples/nextjs-full-stack/.sample.env
- examples/nextjs-full-stack/README.md
- update readme w/ template
- add sample env file
- add demo
> updating README and adding sample env file

- examples/nextjs-oauth/README.md
Adding deploy to Azure video to help devs deploy Next.js app to Azure. This was requested by the community.
> add azure video

- examples/csv-to-mindmap/README.md
Adding video + short to CSV to mindmap app example
> add video + short to README

- examples/breakout-rooms/README.md
added in the storage methods (only app example with these methods)
> Breakout rooms update readme

- catalog-info.yaml
Migrating catalog-info to its own repo
> chore: migrate catalog-info.yaml

- CODEOWNERS
- catalog-info.yaml
Please do not merge until a new "dev-ecosystem" team has been created within the organization
> CADE-388 Update code owners to dev-ecosystem
